package generate_bindings

implemented_types :: []string {
    "void",
    "const unsigned char *",
    "unsigned char *",
    "const char *",
    "char *",
    "int",
    "unsigned int",
    "long",
    "float",
    "double",
    "bool",

    // structs
    "Color",
    "Vector2",
    "Vector3",
    "Vector4",
    "Matrix",
    "Rectangle",
    "Camera",
    "Camera2D",
    "Camera3D",
    "Image",
    "Texture",
    "Texture2D",
    "TextureCubemap",
    "RenderTexture",
    "RenderTexture2D",
    "Quaternion",
    "Ray",
    "RayCollision",
    "BoundingBox",
    "NPatchInfo",
    "GlyphInfo",
    // "Font",
    // "Mesh",
    // "Shader",
    "MaterialMap",
    // "Material",
    "Transform",
    // "BoneInfo",
    // "Model",
    // "ModelAnimation",
    "Ray",
    "RayCollision",
    "Wave",
    // "AudioStream",
    // "Sound",
    // "Music",
    // "VrDeviceInfo",
    // "VrStereoConfig",
    // "FilePathList",
    // "AutomationEvent",
    // "AutomationEventList",

    //
    "Image *",
    "const Vector2 *",
    "Vector2 *",
}

ignore_functions :: []string{"GetWindowHandle"}

funcs_not_yet_implemented :: []string {
    "ExportDataAsCode",
    "LoadFileText",
    "UnloadFileText",
    "UnloadFileData",
    "SaveFileText",
    "LoadImageRaw",
    "LoadImageFromMemory",
    "UnloadUTF8",
    "TextInsert",
    "TextCopy",
    "TextReplace",
    "LoadWaveFromMemory",
    "LoadMusicStreamFromMemory",
    "GetGestureDetected",
    "ComputeCRC32",
    "ColorIsEqual", // deprecated

    //need to implement
    "SetWindowIcons",

    // won't implement
    "GetWindowHandle",
}

array_structs :: []string{"Vector2", "Vector3", "Vector4", "Matrix"}

params_modified_in_place :: []string {
    "ImageFormat.image",
    "ImageToPOT.image",
    "ImageCrop.image",
    "ImageAlphaCrop.image",
    "ImageAlphaClear.image",
    "ImageAlphaMask.image",
    "ImageAlphaPremultiply.image",
    "ImageBlurGaussian.image",
    "ImageKernelConvolution.image",
    "ImageResize.image",
    "ImageResizeNN.image",
    "ImageResizeCanvas.image",
    "ImageMipmaps.image",
    "ImageDither.image",
    "ImageFlipVertical.image",
    "ImageFlipHorizontal.image",
    "ImageRotate.image",
    "ImageRotateCW.image",
    "ImageRotateCCW.image",
    "ImageColorTint.image",
    "ImageColorInvert.image",
    "ImageColorGrayscale.image",
    "ImageColorContrast.image",
    "ImageColorBrightness.image",
    "ImageColorReplace.image",
    "ImageClearBackground.dst",
    "ImageDrawPixel.dst",
    "ImageDrawPixelV.dst",
    "ImageDrawLine.dst",
    "ImageDrawLineV.dst",
    "ImageDrawLineEx.dst",
    "ImageDrawCircle.dst",
    "ImageDrawCircleV.dst",
    "ImageDrawCircleLines.dst",
    "ImageDrawCircleLinesV.dst",
    "ImageDrawRectangle.dst",
    "ImageDrawRectangleV.dst",
    "ImageDrawRectangleRec.dst",
    "ImageDrawRectangleLines.dst",
    "ImageDrawTriangle.dst",
    "ImageDrawTriangleEx.dst",
    "ImageDrawTriangleLines.dst",
    "ImageDrawTriangleFan.dst",
    "ImageDrawTriangleStrip.dst",
    "ImageDraw.dst",
    "ImageDrawText.dst",
    "ImageDrawTextEx.dst",
    "CheckCollisionLines.collisionPoint",
}

ParamArrayPointer :: struct {
    source:     string,
    arrayParam: string,
    countParam: string,
}
// these function parameters are two values in C (a pointer and a count),
// but are a normal array in lua
param_array_pointers :: []ParamArrayPointer {
    {"DrawLineStrip", "points", "pointCount"},
    {"DrawTriangleFan", "points", "pointCount"},
    {"DrawTriangleStrip", "points", "pointCount"},
    {"DrawSplineLinear", "points", "pointCount"},
    {"DrawSplineBasis", "points", "pointCount"},
    {"DrawSplineCatmullRom", "points", "pointCount"},
    {"DrawSplineBezierQuadratic", "points", "pointCount"},
    {"DrawSplineBezierCubic", "points", "pointCount"},
    {"CheckCollisionPointPoly", "points", "pointCount"},
    {"ImageDrawTriangleFan", "points", "pointCount"},
    {"ImageDrawTriangleStrip", "points", "pointCount"},
}

ParamTypeOverride :: struct {
    source:       string,
    source_param: string,
    cast_type:    string,
    type:         string,
}
param_type_overrides :: []ParamTypeOverride {
    // functions
    {"IsWindowState", "flag", "transmute", "rl.ConfigFlags"},
    {"SetWindowState", "flags", "transmute", "rl.ConfigFlags"},
    {"ClearWindowState", "flags", "transmute", "rl.ConfigFlags"},
    {"BeginBlendMode", "mode", "cast", "rl.BlendMode"},
    {"SetConfigFlags", "flags", "transmute", "rl.ConfigFlags"},
    {"SetTraceLogLevel", "logLevel", "cast", "rl.TraceLogLevel"},
    {"IsKeyPressed", "key", "cast", "rl.KeyboardKey"},
    {"IsKeyPressedRepeat", "key", "cast", "rl.KeyboardKey"},
    {"IsKeyDown", "key", "cast", "rl.KeyboardKey"},
    {"IsKeyReleased", "key", "cast", "rl.KeyboardKey"},
    {"IsKeyUp", "key", "cast", "rl.KeyboardKey"},
    {"SetExitKey", "key", "cast", "rl.KeyboardKey"},
    {"IsGamepadButtonPressed", "button", "cast", "rl.GamepadButton"},
    {"IsGamepadButtonDown", "button", "cast", "rl.GamepadButton"},
    {"IsGamepadButtonReleased", "button", "cast", "rl.GamepadButton"},
    {"IsGamepadButtonUp", "button", "cast", "rl.GamepadButton"},
    {"GetGamepadAxisMovement", "axis", "cast", "rl.GamepadAxis"},
    {"IsMouseButtonPressed", "button", "cast", "rl.MouseButton"},
    {"IsMouseButtonDown", "button", "cast", "rl.MouseButton"},
    {"IsMouseButtonReleased", "button", "cast", "rl.MouseButton"},
    {"IsMouseButtonUp", "button", "cast", "rl.MouseButton"},
    {"SetMouseCursor", "cursor", "cast", "rl.MouseCursor"},
    {"SetGesturesEnabled", "flags", "transmute", "rl.Gestures"},
    {"IsGestureDetected", "gesture", "cast", "rl.Gesture"},
    {"GetPixelDataSize", "format", "cast", "rl.PixelFormat"},
    {"SetTextureFilter", "filter", "cast", "rl.TextureFilter"},
    {"SetTextureWrap", "wrap", "cast", "rl.TextureWrap"},
    {"LoadTextureCubemap", "layout", "cast", "rl.CubemapLayout"},
    {"ImageFormat", "newFormat", "cast", "rl.PixelFormat"},
    {"NPatchInfo", "layout", "cast", "rl.NPatchLayout"},
    {"GlyphInfo", "value", "cast", "rune"},

    // structs
    {"Texture", "format", "cast", "rl.PixelFormat"},
    {"Image", "format", "cast", "rl.PixelFormat"},
    {"Camera3D", "projection", "cast", "rl.CameraProjection"},
}

