package generate_bindings

implemented_types :: []string {
    "void",
    "const unsigned char *",
    "unsigned char *",
    "const char *",
    "char *",
    "int",
    "unsigned int",
    "float",
    "double",
    "bool",

    // structs
    "Color",
    "Vector2",
    "Vector3",
    "Vector4",
    "Matrix",
    "Rectangle",
    "Camera",
    "Camera2D",
    "Camera3D",
    "Image",
    "Texture",
    "Texture2D",
    "TextureCubemap",
    "RenderTexture",
    "RenderTexture2D",
    "Quaternion",

    //
    "Image *",
}
skip_functions :: []string {
    "ExportDataAsCode",
    "LoadFileText",
    "UnloadFileText",
    "UnloadFileData",
    "SaveFileText",
    "LoadImageRaw",
    "LoadImageFromMemory",
    "UnloadUTF8",
    "TextInsert",
    "TextCopy",
    "TextReplace",
    "LoadWaveFromMemory",
    "LoadMusicStreamFromMemory",
    "GetGestureDetected",
    "ComputeCRC32",
    "ColorIsEqual", // deprecated

    //need to implement
    "SetWindowIcons",
}

array_structs :: []string{"Vector2", "Vector3", "Vector4", "Matrix"}

params_modified_in_place :: []string {
    "ImageFormat.image",
    "ImageToPOT.image",
    "ImageCrop.image",
    "ImageAlphaCrop.image",
    "ImageAlphaClear.image",
    "ImageAlphaMask.image",
    "ImageAlphaPremultiply.image",
    "ImageBlurGaussian.image",
    "ImageKernelConvolution.image",
    "ImageResize.image",
    "ImageResizeNN.image",
    "ImageResizeCanvas.image",
    "ImageMipmaps.image",
    "ImageDither.image",
    "ImageFlipVertical.image",
    "ImageFlipHorizontal.image",
    "ImageRotate.image",
    "ImageRotateCW.image",
    "ImageRotateCCW.image",
    "ImageColorTint.image",
    "ImageColorInvert.image",
    "ImageColorGrayscale.image",
    "ImageColorContrast.image",
    "ImageColorBrightness.image",
    "ImageColorReplace.image",
    "ImageClearBackground.dst",
    "ImageDrawPixel.dst",
    "ImageDrawPixelV.dst",
    "ImageDrawLine.dst",
    "ImageDrawLineV.dst",
    "ImageDrawLineEx.dst",
    "ImageDrawCircle.dst",
    "ImageDrawCircleV.dst",
    "ImageDrawCircleLines.dst",
    "ImageDrawCircleLinesV.dst",
    "ImageDrawRectangle.dst",
    "ImageDrawRectangleV.dst",
    "ImageDrawRectangleRec.dst",
    "ImageDrawRectangleLines.dst",
    "ImageDrawTriangle.dst",
    "ImageDrawTriangleEx.dst",
    "ImageDrawTriangleLines.dst",
    "ImageDrawTriangleFan.dst",
    "ImageDrawTriangleStrip.dst",
    "ImageDraw.dst",
    "ImageDrawText.dst",
    "ImageDrawTextEx.dst",
}
ParamOverride :: struct {
    source:    string,
    cast_type: string,
    type:      string,
}
param_type_overrides :: []ParamOverride {
    // functions
    {"IsWindowState.flag", "transmute", "ConfigFlags"},
    {"SetWindowState.flags", "transmute", "ConfigFlags"},
    {"ClearWindowState.flags", "transmute", "ConfigFlags"},
    {"BeginBlendMode.mode", "cast", "BlendMode"},
    {"SetConfigFlags.flags", "transmute", "ConfigFlags"},
    {"SetTraceLogLevel.logLevel", "cast", "TraceLogLevel"},
    {"IsKeyPressed.key", "cast", "KeyboardKey"},
    {"IsKeyPressedRepeat.key", "cast", "KeyboardKey"},
    {"IsKeyDown.key", "cast", "KeyboardKey"},
    {"IsKeyReleased.key", "cast", "KeyboardKey"},
    {"IsKeyUp.key", "cast", "KeyboardKey"},
    {"SetExitKey.key", "cast", "KeyboardKey"},
    {"IsGamepadButtonPressed.button", "cast", "GamepadButton"},
    {"IsGamepadButtonDown.button", "cast", "GamepadButton"},
    {"IsGamepadButtonReleased.button", "cast", "GamepadButton"},
    {"IsGamepadButtonUp.button", "cast", "GamepadButton"},
    {"GetGamepadAxisMovement.axis", "cast", "GamepadAxis"},
    {"IsMouseButtonPressed.button", "cast", "MouseButton"},
    {"IsMouseButtonDown.button", "cast", "MouseButton"},
    {"IsMouseButtonReleased.button", "cast", "MouseButton"},
    {"IsMouseButtonUp.button", "cast", "MouseButton"},
    {"SetMouseCursor.cursor", "cast", "MouseCursor"},
    {"SetGesturesEnabled.flags", "transmute", "Gestures"},
    {"IsGestureDetected.gesture", "cast", "Gesture"},
    {"GetPixelDataSize.format", "cast", "PixelFormat"},
    {"SetTextureFilter.filter", "cast", "TextureFilter"},
    {"SetTextureWrap.wrap", "cast", "TextureWrap"},
    {"LoadTextureCubemap.layout", "cast", "CubemapLayout"},
    {"ImageFormat.newFormat", "cast", "PixelFormat"},

    // structs
    {"Texture.format", "cast", "PixelFormat"},
    {"Image.format", "cast", "PixelFormat"},
    {"Camera3D.projection", "cast", "CameraProjection"},
}

